# Generated by Django 3.1.5 on 2021-03-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vk_user_id',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='vk_user_login',
            fields=[
                ('login', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='vk_user_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vkauth.vk_user_login')),
            ],
        ),
        migrations.CreateModel(
            name='vk_user_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vkauth.vk_user_id')),
            ],
        ),
    ]
