# Generated by Django 3.1.5 on 2021-03-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vk_user_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='vkuser',
        ),
        migrations.CreateModel(
            name='vk_user_token',
            fields=[
                ('token', models.CharField(max_length=1000)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vkauth.vk_user_id')),
            ],
        ),
    ]
