# Generated by Django 3.1.5 on 2021-04-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vk_user_token',
            name='login',
        ),
        migrations.AddField(
            model_name='vk_user_token',
            name='token',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
