# Generated by Django 3.1.5 on 2021-03-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkauth', '0002_auto_20210318_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='vk_user_token',
            name='login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vkauth.vk_user_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vk_user_token',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
