# Generated by Django 3.1.5 on 2021-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkauth', '0003_auto_20210318_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='vk_user_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reach_by_week', models.CharField(max_length=1000)),
            ],
        ),
    ]
