# Generated by Django 3.1.5 on 2021-01-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16)),
                ('user_email', models.EmailField(max_length=32, unique=True, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_social_vk', models.URLField(max_length=40)),
                ('user_social_inst', models.URLField(max_length=40)),
            ],
        ),
    ]
